project:
  type: website

website:
  title: Decoding E-Commerce Trends and Insights 
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO-526-F24/project-01-Pacman
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: Dashboard
        href: dashboard.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true

execute:
  freeze: auto
